### ISSUE TITLE
Current docker host not working in Terraform version 1.1.9

### ISSUE THREAD

**Issue by llauderesv** [hashicorp/learn-terraform-import#11]
This is not working anymore with Terraform version 1.19

```terraform
provider "docker" {
  host    = "npipe:////.//pipe//docker_engine"
}
```
I'm getting this error.

![Screen Shot 2022-05-09 at 10 02 04 AM](https://user-images.githubusercontent.com/20419473/167328199-bbe8f68d-e8c5-4575-968c-1623f533b1fe.jpg)

But when I used the updated provider that was used [here](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs#example-usage) in the documentation it's working.

**Comment by joegraviton** [comment]
I have to use this on ubuntu 20.04, tf 1.19:
```
provider "docker" {
    host = "unix:///var/run/docker.sock"
}
```

**Comment by llauderesv** [comment]
Yea, maybe they should update the code to the latest version

**Comment by joegraviton** [comment]
Also, this whole import process is more like a hack, other than a official tutorial.
I do hope it can be less painful and scary ...

**Comment by judithpatudith** [comment]
Hi all, thanks so much for this report! It's on our list now :)
